# Generated by Django 3.1.7 on 2021-04-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=70, verbose_name='Email to holders')),
                ('topic', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
    ]
